spring:
  datasource:
    #url: jdbc:mysql://47.121.204.175:3306/bullet_screen_video_website
    url: jdbc:mysql://localhost:3306/bullet_screen_video_website
    username: root
    password: LHSqaz123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size:
        1GB
      max-file-size:
        1GB
server:
  port  : 8080

