spring:
  datasource:
    url: jdbc:mysql://8.130.127.47:3306/bullet_screen_video_website
    username: root
    password: LHSqaz123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size:
        1GB
      max-file-size:
        1GB

